import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import { LoadingProvider } from "@/app/contexts/LoadingContext";
import LoadingOverlay from "@/components/LoadingOverlay";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className="relative text-gray-800 font-sans antialiased">
        {/* ▼ 背景アニメーション */}
        <div className="absolute inset-0 -z-10 animate-gradient"></div>

        {/* ▼ コンテンツ */}
        <LoadingProvider>
          {/* <BodyScrollLock /> */}
          <LoadingOverlay />
          <div className="relative z-20 overflow-x-hidden">{children}</div>
        </LoadingProvider>
      </body>
    </html>
  );
}
